### ISSUE TITLE
Error:32 Broken pipe

### ISSUE THREAD

**Issue by dsenthilraj** [piuccio/sublime-esformatter#12]
Installed ESFormatter for Sublime Text3 when try to use it using Ctrl +Alt+ F. I get Broken Pipe.

**Comment by qoozy** [comment]
I have the same problem.
What's should I do?
+1

**Comment by piuccio** [comment]
Version `1.6.3` is broken, see #51 

Can you please upgrade to `1.6.4` and try again? Btw keep in mind that it doesn't format JSON, only valid JS.

**Comment by qoozy** [comment]
It worked! Thanks piuccio!
