### ISSUE TITLE
error: Error (2):Unable to format

### ISSUE THREAD

**Issue by doque** [piuccio/sublime-esformatter#41]
I'm trying to format this code, which includes JSX for a ReactJS component:

    var CommentBox = React.createClass({
        render: function() {
            return ( <div className = "commentBox">
                Hello, world! I am a CommentBox.</div>
            );
        }
    });

Pressing `cmd+alt+f` results in a popup with the message
> error: Error (2):Unable to format

There are no further errors in the console.

**Comment by piuccio** [comment]
JSX is not valid javascript. The solution is to allow esformatter plugins, tracked in #40
