### ISSUE TITLE
Plugin doesn't pick up PATH from shell

### ISSUE THREAD

**Issue by 0x80** [piuccio/sublime-esformatter#47]
I'm getting this error

```
It looks like node is not installed.
Please make sure that node.js is installed and in your PATH
```

I have Node installed using NVM. This means the binary is located in a path depending on the currently active version. This path is dynamic and needs to be added to PATH when the shell initializes. 

I had a similar issue with sublime linter but this plugin has a debug mode which prints the PATH in the sublime console. The problem there was that sublime uses a login shell as opposed to an interactive shell and therefor you need to make sure the NVM initialization happens in ~/.profile (or ~/.zprofile for zsh)

The debug output from sublime linter now shows the correct paths in the sublime console, listing the iojs (node) directory:
```
SublimeLinter: user shell: /bin/zsh 
SublimeLinter: computed PATH using /bin/zsh:
/Users/me/.nvm/versions/io.js/v2.2.1/bin
/usr/local/bin
/usr/local/sbin
/usr/bin
/bin
/usr/sbin
/sbin
```

So my questions is, why doesn't esformatter pick this up? What path is it referring to? 

I've also added the NVM path to the bash shell, but this didn't help.

**Comment by piuccio** [comment]
Try changing this in your esformatter user settings

```
{
    // Path to the node executable, by default it tries to resolve the executable
    // for the command 'node' or 'nodejs'. Change this value to specify your own path
    "nodejs_path": null
}
```

**Comment by 0x80** [comment]
What do you mean? Set a fixed path? It changes...

**Comment by piuccio** [comment]
All that esformatter does is try to run `nodejs` and `node` using `subprocess.Popen`. No idea what happens behind `Popen`.

You could try setting `nodejs_path` to `nvm exec 0.10 node`

**Comment by akloeber** [comment]
Another option would be to set `NVM_SYMLINK_CURRENT`to `true` (see documentation on https://github.com/creationix/nvm). Then after each `nvm use` a symlink at `~/.nvm/current` is created/updated that points to your selected node version.

In addition to that you still have to configure `nodejs_path` in the sublime package: ```
```
{
  "nodejs_path": "<YOUR_HOME_DIR>/.nvm/current/bin/node"
}
```

**Comment by 0x80** [comment]
Thanks, that will do :+1:
