### ISSUE TITLE
Add support for .editorconfig

### ISSUE THREAD

**Issue by Palid** [piuccio/sublime-esformatter#56]
Some projects I work with have different styling guides and we all use .editorconfig for that. Esformatter doesn't care for .editorconfig and makes me add yet another dotfile to the repo. Is it possible to make it  see .editorconfig style-guide?

**Comment by piuccio** [comment]
I'm not interested in adding support for that, especially considering that there's a pretty good plugin already available https://github.com/sindresorhus/editorconfig-sublime

**Comment by Palid** [comment]
@piuccio The problem is that esformatter doesn't care for editorconfig files and forces 2spaces everywhere. Even though eslintrc says four and editorconfig does the same. Do we really need another dotfile in the repository, when there are already two for the same thing?

**Comment by piuccio** [comment]
`.editorconfig` and `. eslintrc ` only have a subset of configuration options that are meaningful for `esformatter`. I don't think it's a good design decision to infer options from some other tools configuration files. I won't do it inside this project, but if you convince [esformatter](https://github.com/millermedeiros/esformatter) itself to support `.editorconfig`, then you'll automatically have support for it inside sublime-esformatter.
