### ISSUE TITLE
getNpmGlobalRoot fails on Windows

### ISSUE THREAD

**Issue by jan11011977** [piuccio/sublime-esformatter#58]
getNpmGlobalRoot currently always fails on Windows because it's not searching for "npm" in the path.

This can be easily fixed by adding "shell=True" to line 19 of esformatter.py, like so:

        return subprocess.check_output(["npm", "root", "-g"], shell=True).rstrip().decode('utf-8')

Thanks

**Comment by piuccio** [comment]
mind creating a PR?

**Comment by piuccio** [comment]
Things have changed a bit with `2.0.0`, I'm closing this, let me know if you still have problems
