### ISSUE TITLE
how to indent JSX syntax?

### ISSUE THREAD

**Issue by littlee** [piuccio/sublime-esformatter#60]
after formating the code, all the code is pretty but the jsx syntax.
jsx syntax leave unchanged at all.

how to make the formatter to indent jsx?
![2016-01-16_155820](https://cloud.githubusercontent.com/assets/7534668/12371323/432c86ba-bc6a-11e5-8cd9-77890d0be025.png)

**Comment by piuccio** [comment]
there's a PR open, #53, but I can't merge it yet because new esformatter doesn't work properly when packaged.

I need more time to find a solution (or help)

**Comment by littlee** [comment]
good luck :smiley:

**Comment by piuccio** [comment]
As of `2.0.0` the plugin uses the local/global version of esformatter, you can configure your jsx plugin there.
