### ISSUE TITLE
How to use esformatter plugin in sublime text 3

### ISSUE THREAD

**Issue by huntout** [piuccio/sublime-esformatter#61]
my `.esformatter` file

```json
{
  "preset": "default",

  "plugins": [
    "esformatter-add-trailing-commas",
    "esformatter-quotes",
  ],

  "pipe": {
    "after": [
      "es-strip-semicolons",
    ],
  },

  "quotes": {
    "type": "single",
  },
}
```

my `package.json` file

``` json
{
  "devDependencies": {
    "es-strip-semicolons": "^1.0.6",
    "esformatter": "^0.8.2",
    "esformatter-add-trailing-commas": "^1.1.0",
    "esformatter-quotes": "^1.0.3",
  }
}
```

It seems the plugins not work.

**Comment by piuccio** [comment]
did you install `esformatter` globally? `npm install -g esformatter`

**Comment by huntout** [comment]
yes, I have installed `esformatter` glabally too.

**Comment by hugomrdias** [comment]
i have the same problem console shows this error

error: Error (1):Unable to format

**Comment by huntout** [comment]
I have resolved it.

```batch
cd "Sublime Text 3 x64\Data\Packages\EsFormatter\lib"
npm i -S esformatter esformatter-add-trailing-commas esformatter-quotes
npm run prepublish
```

**Comment by andy9775** [comment]
@hugomrdias I had the same issue. Try adding the plugins that your .esformatter file declares to `~/Library/Application Support/Sublime Text 3/Packages/EsFormatter/lib` by using `npm i -S <package-name>` then `npm run prepublish`

**Comment by piuccio** [comment]
As of `2.0.0` the plugin uses the local/global version of esformatter, it should be easier to configure your plugins.
